[supervisord]
nodaemon=true

[program:laravel-start]
command=/usr/local/bin/php /var/www/html/artisan serve --host=0.0.0.0 --port=9000
autostart=true
autorestart=true
redirect_stderr=true
stderr_logfile=/var/log/laravel-queue.err.log
stdout_logfile=/var/log/laravel-queue.out.log
user=www-data
directory=/var/www/html
stopwaitsecs=3600
stopasgroup=true
killasgroup=true


